blog2/urls.py
from django.contrib import admin
from django.urls import include, path

#from blog_app.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('index/',index,name='index'),  
    path('myblog/',include(('blog_app.urls','blog_app'),namespace='blog_app'))
]
 

blog_app/urls.py
'''
Created on 2019年7月26日

@author: Jonny
'''

from django.urls.conf import path


from . import views 



urlpatterns=[
    path('index/', views.index,name='index_page'),
    path('article/<int:article_id>/',views.article_page,name='article_page'),
    path('edit/<int:article_id>/',views.edit_page,name='edit_page'),
    path('edit/action/',views.edit_action,name='edit_action')
]

blog_app/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=32,default='Title')
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

blog_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models

# Create your views here.
def index(request):
    articles=models.Article.objects.all()
    return render(request,"blog_app/index.html",{'articles':articles})


def article_page(request,article_id):
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog_app/article_page.html',{'article':article}) 


def edit_page(request,article_id):
    if str(article_id) =='0':
        return render(request,'blog_app/edit_page.html')
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog_app/edit_page.html',{'article':article})


def edit_action(request):
    title=request.POST.get('title','NEW ARTICLE')
    content=request.POST.get('content','CONTENT')
    article_id=request.POST.get('article_id','0')
    if article_id=='0':
        models.Article.objects.create(title=title,content=content)
        articles=models.Article.objects.all()
        return render(request,"blog_app/index.html",{'articles':articles})
    else:
        article=models.Article.objects.get(pk=article_id)
        article.title=title
        article.content=content
        article.save()
        return render(request,'blog_app/article_page.html',{'article':article})
        

blog_app/templates/blog_app/article_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Article page</title> 
<style>
div{ 
	margin-left:150px; 
	width:666px;
}
body{
	background:url(http://file.hanfcn.com/attachment/webbg/20171213/hanfcn.com_20171213112354ttdbfxa5qua.jpg) no-repeat center;
	background-size: 100% 100%;
    background-attachment: fixed;
}
</style>
</head>
<body>
	<div>
		<h1>{{article.title}}</h1>
		<br /><br />
		<h3>{{article.content}}</h3>
		<br />
		<br /> <a href={%url 'blog_app:edit_page' article.id %}>modify article</a>
	</div>
</body>
</html>

blog_app/templates/blog_app/edit_page.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edit page</title>

<style type='text/css'>
form{
	margin-left:100px;
	text_align:left;
}
.title{
	width:600px;
	height:auto;
	word-break:break-all;
}
.content{
	width:600px;
	height:200px;
	word-break:break-all;
}
body{
	background:url(http://file.hanfcn.com/attachment/webbg/20171213/hanfcn.com_20171213112354ttdbfxa5qua.jpg) no-repeat center;
	background-size: 100% 100%;
    background-attachment: fixed;
}
</style>
</head>
<body >
	<form action={% url 'blog_app:edit_action' %} method="post">
		{% csrf_token %} 
		<input type='hidden' name='article_id' value='{{article.id | default:"0"}}'>
		<label><h1>博客编辑</h1></label>
		<br/><br/>
		<label><h2>标题:<br/><input class='title' type="text" text-align:center name='title' value="{{article.title}}"></h2></label><br /> 
		<label><h2>内容:<br/><br/><input class='content' type="text" text-align:center name="content" value="{{article.content}}"></h2></label>
		<br /><br /><br /><br /><br /> 
		<div style='text-align:right;width:600px;'><input type="submit" name="submit"></div>
	</form>
</body>
</html>

blog_app/templates/blog_app/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>My blog</title>
<style>
li{
	border-bottom:1px dotted #ccc;
	height:50px;
}
div{
	margin-left:150px;
}
body{
	background:url(http://file.hanfcn.com/attachment/webbg/20171213/hanfcn.com_20171213112354ttdbfxa5qua.jpg) no-repeat center;
	background-size: 100% 100%;
    background-attachment: fixed;
}
</style>
</head>
<body>
	<div>
		<h1>
			<a href={%url 'blog_app:edit_page' 0 %}>新建博客</a>
			<br/><br/><br/>
		</h1>
	</div>
	<div>
		<h1>博客列表：</h1>
		{% for article in articles %} 
		<li><a href="{% url 'blog_app:article_page' article.id %}">{{article.title}}</a><br/></li>
		{% endfor %}
	</div>
</body>
</html>